# Generated by Django 4.0.5 on 2022-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='page',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sku',
        ),
        migrations.AddField(
            model_name='course',
            name='Course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(to='instructors.course'),
        ),
    ]
