# Generated by Django 4.0.5 on 2022-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_remove_course_name_remove_course_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course',
            field=models.CharField(max_length=200),
        ),
    ]
