# Generated by Django 4.0.5 on 2022-07-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_instructor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
    ]
