# Generated by Django 4.0.5 on 2022-07-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_rename_course_course_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='page',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='sku',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(to='instructors.course'),
        ),
    ]
